services:
  directus:
    image: directus/directus:11.17.0
    container_name: tilikkota-be
    restart: unless-stopped
    ports:
      - "8055:8055"
    # network_mode: "host"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    env_file:
      - .env
    environment:
      KEY: "my-secret-key"
      SECRET: "my-secret"

      DB_CLIENT: "pg"
      DB_CONNECTION_STRING: ${DB_URI}

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin123"

      PUBLIC_URL: "http://directus-example:8055"
